version: '3.9'

services:
  grpc-service:
    build:
      context: ./grpc-service
      dockerfile: Dockerfile
    container_name: grpc-service
    ports:
      - "50051:50051"
    restart: unless-stopped

  rest-service:
    build:
      context: ./rest-service
      dockerfile: Dockerfile
    container_name: rest-service
    ports:
      - "8080:8080"
    # depends_on:
    #   - grpc-service
    restart: unless-stopped